### ISSUE TITLE
AccessDeniedException

### ISSUE THREAD

**Issue by eraserfusion** [maciejtreder/serverless-apigw-binary#19]
Starting in version 0.3.7 I am no longer able to deploy with this plugin. The following is the error log when deploying:

```
/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: AccessDeniedException: User: arn:aws:iam::**************:user/********** is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:us-east-1::/restapis
    at Object.extractError (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/json.js:48:27)...
```

The resource that I am failing to authorize for looks like it is missing some information `arn:aws:apigateway:us-east-1::/restapis`.

If I reinstall this plugin with 0.3.6 my project deploys without a problem.

**Comment by maciejtreder** [comment]
Hello. Thank you for the report. Could you share your ```serverless.yml``` content?

**Comment by eraserfusion** [comment]
It's fairly large, but I think the relevant parts are included here:

```
service: service-name

frameworkVersion: "=1.18.1"

provider:
  name: aws
  runtime: nodejs6.10
  role: arn:aws:iam::lambda-role
  apiKeys:
    - ${self:service}-test-${self:custom.myStage}
  usagePlan:
    throttle:
      burstLimit: 1000
      rateLimit: 1000
  environment:
    serviceName: ${self:service}

plugins:
 - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - 'application/xml'
      - 'application/java-archive'
  myStage: ${opt:stage, self:provider.stage}
```
