### ISSUE TITLE
Is it possible to use this plugin locally?

### ISSUE THREAD

**Issue by gitowiec** [maciejtreder/serverless-apigw-binary#30]
I would like to use this plugin when calling `serverless webpack serve --function run` locally for development. I did it but the `event` parameter does not contain file content (I use Postman with POST and binary file in body)
Here's my serverless.yml:
```
service: serverless-chrome

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-2
  environment:
    CHROME_PATH: ${opt:chromepath, './headless-chrome/headless_shell'}

custom:
  webpackIncludeModules: false # disable auto including modules
  apigwBinary:
      types:           #list of mime-types
        - 'application/zip'
        - 'application/octet-stream'
        - 'application/x-zip-compressed'
        - 'text/html'
        - 'text/plain'
        - 'text/css'
        - 'text/javascript'

plugins:
  - serverless-webpack
  - serverless-apigw-binary

functions:
  run:
    description: Run headless Chromium
    memorySize: 1536
    timeout: 30
    handler: handler.run

    events:
      - http:
          path: package
          method: post
```
