### ISSUE TITLE
Support deployment to different stages

### ISSUE THREAD

**Issue by NickPyae** [maciejtreder/serverless-apigw-binary#8]
I tried to deploy my serverless project to dev stage and `multipart/form-data` content type was not created in Binary Support in API Gateway even though I specified it it serverless.yml like this

```
custom:
  apigwBinary:
    types:           
      - 'multipart/form-data'
```

I am trying to deploy my current project to different stages dev, staging and prod.
